// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Util;
    return Util = (function() {
      function Util() {}

      Util.debug = function() {
        return console.log.apply(null, arguments);
      };

      return Util;

    })();
  });

}).call(this);
