// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: 'script/',
    paths: {
      jquery: 'vendor/jquery-2.0.3.min',
      app: 'application/'
    }
  });

  define(['jquery', 'app/MapGenerator'], function($, MapGenerator) {
    return $(document).ready(function() {
      var map;
      console.log("Hello world");
      map = new MapGenerator();
      return map.webGLStart();
    });
  });

}).call(this);
