// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'vendor/gl-matrix-min'], function($, glMatrix) {
    var MapGenerator;
    return MapGenerator = (function() {
      function MapGenerator() {}

      MapGenerator.prototype.webGLStart = function() {
        var canvas;
        canvas = document.getElementById("#map");
        this.initGL(canvas);
        this.initShaders();
        this.initBuffers();
        gl.clearColor(0.0, 0.0, 0.0, 1.0);
        gl.enable(gl.DEPTH_TEST);
        return drawScene();
      };

      return MapGenerator;

    })();
  });

}).call(this);
