// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'vendor/gl-matrix-min', 'app/libs/utils'], function($, glMatrix, Utils) {
    var MapGenerator;
    return MapGenerator = (function() {
      function MapGenerator() {}

      MapGenerator.prototype.webGLStart = function() {
        var canvas;
        canvas = document.getElementById("map");
        this.initGL(canvas);
        this.initShaders();
        this.initBuffers();
        return this.drawScene();
      };

      MapGenerator.prototype.initGL = function(canvas) {
        var e;
        try {
          this.gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl');
          this.gl.viewportWidth = canvas.width;
          return this.gl.viewportHeight = canvas.height;
        } catch (_error) {
          e = _error;
          return Utils.debug("Exception catched", e.toString());
        }
      };

      MapGenerator.prototype.initShaders = function() {};

      MapGenerator.prototype.initBuffers = function() {};

      MapGenerator.prototype.drawScene = function() {};

      return MapGenerator;

    })();
  });

}).call(this);
